In [88]:
import plotly

import pandas as pd
import numpy as np
import datetime as dt
import pickle


# visualization imports
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')

%matplotlib inline

# modelling imports
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.decomposition import PCA
from sklearn.metrics import roc_curve, auc
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.metrics import precision_recall_curve,f1_score, fbeta_score
from sklearn import tree
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
import random
#import mplleaflet
import geopandas as gpd

from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
from sqlalchemy import Table, Integer,MetaData, ForeignKey

import googlemaps
from googleplaces import GooglePlaces, types, lang
import geopandas as gpd
from shapely.geometry import Point
import geopy.distance

from IPython.display import SVG
from graphviz import Source
from IPython.display import display                               
from ipywidgets import interactive

import warnings
warnings.filterwarnings("ignore")

In [23]:
df2=pd.read_csv('DSI_kickstarterscrape_dataset.csv',encoding='latin-1')

with open('city_density.pkl','rb') as picklefile:
    df_cities=pickle.load(picklefile)

In [26]:
API_KEY = input()
google_places = GooglePlaces(API_KEY)
gmaps = googlemaps.Client(key = API_KEY)

AIzaSyCTymNJGVf8QjlwQLLIvfknhvT2YLOOuf4

In [12]:
plotly.tools.set_credentials_file(username='williamcottrell72', api_key='Y4gzZWD6jrcwgmojgZRs')

In [29]:
with open('fixed_df','rb') as file:
    df_fixed=pickle.load(file)

In [49]:
cats=set(df_fixed['category'])

(38526, 25)

In [55]:
df_success=(df_fixed[df_fixed.status=='successful'])[['category','location']]

In [65]:

random=np.random.choice(list(range(len(df_success))),1000)
df_success2=df_success.iloc[random]

In [31]:
succ_cities=df_fixed[df_fixed.status=='successful'].location.values

In [66]:
succ_dct={}
for c in cats:
    cities=df_success2[df_success2.category==c].location.values
    lat=[]
    long=[]
    for city in cities:
        geocode_result = gmaps.geocode(city)[0]
        gr_geometry = geocode_result['geometry']
        gr_location = gr_geometry['location']
        gr_lat = gr_location['lat']+np.random.normal(0,.2)
        gr_lng = gr_location['lng']+np.random.normal(0,.2)
        lat.append(gr_lat)
        long.append(gr_lng)
    succ_dct[c]=[lat,long]

In [76]:
len(succ_dct['Art'][0])

93

In [ ]:
lat=[]
long=[]
np.random.shuffle(succ_cities)
for c in succ_cities[:5000]:
    geocode_result = gmaps.geocode(c)[0]
    gr_geometry = geocode_result['geometry']
    gr_location = gr_geometry['location']
    gr_lat = gr_location['lat']+np.random.normal(0,.2)
    gr_lng = gr_location['lng']+np.random.normal(0,.2)
    lat.append(gr_lat)
    long.append(gr_lng)

In [13]:
import plotly.plotly as py
import plotly.graph_objs as go

trace0 = go.Scatter(
    x=[1, 2, 3, 4],
    y=[10, 15, 13, 17]
)
trace1 = go.Scatter(
    x=[1, 2, 3, 4],
    y=[16, 5, 11, 9]
)
data = [trace0, trace1]

py.iplot(data, filename = 'basic-line')

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~williamcottrell72/0 or inside your plot.ly account where it is named 'basic-line'

In [87]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_us_cities.csv')
df.head()

df['text'] = df['name'] + '<br>Population ' + (df['pop']/1e6).astype(str)+' million'
limits = [(0,2),(3,10),(11,20),(21,50),(50,3000)]
colors = ["rgb(0,116,217)","rgb(255,65,54)","rgb(133,20,75)","rgb(255,133,27)","rgb(120,120,10)","rgb(140,100,20)",\
          "rgb(100,160,90)","rgb(80,180,69)","rgb(60,200,50)","rgb(40,210,40)","rgb(20,20,2)","rgb(1,1,1)",\
          "rgb(2,200,200)","rgb(7,8,18)"]
cities = []
scale = 5000

cat_list=list(cats)

for i in range(len(cat_list)):
    #lim = limits[i]
    #df_sub = df[lim[0]:lim[1]]
    city = dict(
        type = 'scattergeo',
        locationmode = 'USA-states',
        lon = succ_dct[cat_list[i]][1],
        lat = succ_dct[cat_list[i]][0],
        text = cat_list[i],
        marker = dict(
            size = df_sub['pop']/scale,
            color = colors[i],
            line = dict(width=0.5, color='rgb(40,40,40)'),
            sizemode = 'area'
        ),
        #name = '{0} - {1}'.format(lim[0],lim[1])
        name=cat_list[i])
    cities.append(city)

layout = dict(
        title = 'Succesful Campaigns By Category<br>(Click legend to toggle traces)',
        showlegend = True,
        geo = dict(
            scope='usa',
            projection=dict( type='albers usa' ),
            showland = True,
            landcolor = 'rgb(217, 217, 217)',
            subunitwidth=1,
            countrywidth=1,
            subunitcolor="rgb(255, 255, 255)",
            countrycolor="rgb(255, 255, 255)"
        ),
    )

fig = dict( data=cities, layout=layout )
py.iplot( fig, validate=False, filename='d3-bubble-map-populations' )

In [80]:
len(cats)

14

In [47]:
df

,name,pop,lat,lon,text
0,New York,8287238,40.730599,-73.986581,New York <br>Population 8.287238 million
1,Los Angeles,3826423,34.053717,-118.242727,Los Angeles <br>Population 3.826423 million
2,Chicago,2705627,41.875555,-87.624421,Chicago <br>Population 2.705627 million
3,Houston,2129784,29.758938,-95.367697,Houston <br>Population 2.129784 million
4,Philadelphia,1539313,39.952335,-75.163789,Philadelphia <br>Population 1.539313 million
5,Phoenix,1465114,33.446768,-112.075672,Phoenix <br>Population 1.465114 million
6,San Antonio,1359174,29.424600,-98.495141,San Antonio <br>Population 1.359174 million
7,San Diego,1321016,32.717421,-117.162771,San Diego <br>Population 1.321016 million
8,Dallas,1219399,32.776196,-96.796899,Dallas <br>Population 1.219399 million
9,San Jose,971495,37.343850,-121.883135,San Jose <br>Population 0.971495 million
10,Austin,839714,30.271129,-97.743700,Austin <br>Population 0.839714 million
11,Jacksonville,829543,30.332184,-81.655651,Jacksonville <br>Population 0.829543 million
12,Indianapolis,827346,39.768333,-86.158350,Indianapolis <br>Population 0.827346 million
13,San Francisco,816239,37.779277,-122.419270,San Francisco <br>Population 0.816239 million
14,Columbus,799270,39.962260,-83.000706,Columbus <br>Population 0.79927 million
15,Fort Worth,761895,32.753177,-97.332746,Fort Worth <br>Population 0.761895 million
16,Charlotte,756204,35.227087,-80.843127,Charlotte <br>Population 0.756204 million
17,Detroit,702149,42.348664,-83.056737,Detroit <br>Population 0.702149 million
18,El Paso,665503,31.811131,-106.501349,El Paso <br>Population 0.665503 million
19,Memphis,655975,35.149022,-90.051629,Memphis <br>Population 0.655975 million
20,Boston,630645,42.360482,-71.059568,Boston <br>Population 0.630645 million
21,Seattle,622175,47.603832,-122.330062,Seattle <br>Population 0.622175 million
22,Baltimore,620889,39.290861,-76.610807,Baltimore <br>Population 0.620889 million
23,Washington,620427,38.894955,-77.036646,Washington <br>Population 0.620427 million
24,Denver,619390,39.739154,-104.984703,Denver <br>Population 0.61939 million
25,Nashville-Davidson,612243,36.187025,-86.780862,Nashville-Davidson <br>Population 0.612243 m...
26,Louisville/Jefferson County,601709,38.209237,-85.703850,Louisville/Jefferson County <br>Population 0...
27,Milwaukee,597435,43.034993,-87.922497,Milwaukee <br>Population 0.597435 million
28,Portland,593859,45.520247,-122.674195,Portland <br>Population 0.593859 million
29,Oklahoma City,589896,35.472989,-97.517054,Oklahoma City <br>Population 0.589896 million
...,...,...,...,...,...
3198,Escalon,7208,37.754457,-121.006422,Escalon <br>Population 0.007208 million
3199,Mount Carmel,7208,38.410880,-87.761417,Mount Carmel <br>Population 0.007208 million
3200,Alamo Heights,7201,29.484953,-98.465850,Alamo Heights <br>Population 0.007201 million
3201,Devils Lake,7185,48.112779,-98.865120,Devils Lake <br>Population 0.007185 million
3202,Midland Park borough,7185,40.989264,-74.140699,Midland Park borough<br>Population 0.007185 mi...
3203,Logan,7176,40.107509,-89.376854,Logan <br>Population 0.007176 million
3204,Milton,7176,42.249544,-71.066161,Milton <br>Population 0.007176 million
3205,Woodland Park,7171,39.009936,-105.045003,Woodland Park <br>Population 0.007171 million
3206,Navasota,7170,30.387414,-96.087507,Navasota <br>Population 0.00717 million
3207,Catoosa,7165,34.891114,-85.131315,Catoosa <br>Population 0.007165 million
3208,Hudsonville,7155,42.870859,-85.865036,Hudsonville <br>Population 0.007155 million
3209,Ashland,7153,38.478414,-82.637939,Ashland <br>Population 0.007153 million
3210,Highland Heights,7153,41.551995,-81.478452,Highland Heights <br>Population 0.007153 million
3211,Sioux Center,7148,43.079691,-96.175672,Sioux Center <br>Population 0.007148 million
3212,Glenolden borough,7143,39.900113,-75.289074,Glenolden borough<br>Population 0.007143 million
3213,Pinson,7142,33.688991,-86.683323,Pinson <br>Population 0.007142 million
3214,Independence,7137,37.224236,-95.708313,Independence <br>Population 0.007137 million
3215,Clewiston,7134,26.754231,-80.933675,Clewiston <br>Population 0.007134 million
3216,Delphos,7128,40.843383,-84.341618,Delphos <br>Population 0.007128 million
3217,University Park village,7127,34.182697,-117.333909,University Park village<br>Population 0.007127...
3218,Huron,7122,44.792307,-82.331130,Huron <br>Population 0.007122 million
3219,Delafield,7122,43.061028,-88.404069,Delafield <br>Population 0.007122 million
3220,La Junta,7116,37.985009,-103.543832,La Junta <br>Population 0.007116 million
3221,New Square village,7109,41.167039,-74.043197,New Square village<br>Population 0.007109 million
3222,Sullivan,7104,36.496667,-82.286903,Sullivan <br>Population 0.007104 million
3223,Spanish Fort,7102,30.674913,-87.915272,Spanish Fort <br>Population 0.007102 million
3224,Plaquemine,7102,30.289083,-91.234274,Plaquemine <br>Population 0.007102 million
3225,Milton-Freewater,7102,45.932635,-118.387743,Milton-Freewater <br>Population 0.007102 million
3226,Benton,7096,36.034529,-88.101285,Benton <br>Population 0.007096 million
3227,Ocean City,7094,39.277616,-74.574600,Ocean City <br>Population 0.007094 million